version: "2"
services:

  zookeeper-1:
    container_name: zookeeper-1    
    networks: ["vnet"]
    hostname: zookeeper-1.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 1 1 vnet

  drillbit-1:
    container_name: drillbit-1
    networks: ["vnet"]
    hostname: drillbit-1.vnet
    image: smizy/apache-drill:1.15.0-alpine
    ports: 
      - 8047
    depends_on: ["zookeeper-1"]  
    environment:
      - SERVICE_8047_NAME=drillbit
      - DRILL_HEAP=512M 
      - DRILL_MAX_DIRECT_MEMORY=1G   
      - DRILL_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181 
      

networks:
  vnet:
    external:
      name: vnet 
